/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 58
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_local = 1,
  anon_sym_SEMI = 2,
  anon_sym_EQ = 3,
  anon_sym_COMMA = 4,
  anon_sym_let = 5,
  sym_identifier = 6,
  sym_integer = 7,
  sym_float = 8,
  sym_string_content = 9,
  sym_interpolated_string_content = 10,
  anon_sym_DQUOTE = 11,
  anon_sym_DOLLAR_DQUOTE = 12,
  anon_sym_LBRACE = 13,
  anon_sym_RBRACE = 14,
  anon_sym_AT_DQUOTE = 15,
  anon_sym_DQUOTE_DQUOTE = 16,
  anon_sym_true = 17,
  anon_sym_false = 18,
  anon_sym_PLUS_PLUS = 19,
  anon_sym_DASH_DASH = 20,
  anon_sym_DASH = 21,
  anon_sym_BANG = 22,
  anon_sym_TILDE = 23,
  anon_sym_PLUS = 24,
  anon_sym_STAR = 25,
  anon_sym_SLASH = 26,
  anon_sym_PERCENT = 27,
  sym_comment = 28,
  sym_source_file = 29,
  sym__statement = 30,
  sym_local_statement = 31,
  sym__initVar = 32,
  sym_let_statement = 33,
  sym__expression = 34,
  sym_number = 35,
  sym_string = 36,
  sym_simple_string = 37,
  sym_interpolated_string = 38,
  sym_interpolation = 39,
  sym_verbatim_string = 40,
  sym_verbatim_quotes = 41,
  sym_boolean = 42,
  sym_unary_expression = 43,
  sym__unary_post_expression = 44,
  sym__unary_pre_expression = 45,
  sym_binary_expression = 46,
  sym_add = 47,
  sym_substract = 48,
  sym_multiply = 49,
  sym_divide = 50,
  sym_mod = 51,
  aux_sym_source_file_repeat1 = 52,
  aux_sym_interpolated_string_repeat1 = 53,
  aux_sym_verbatim_string_repeat1 = 54,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_local] = "local",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [anon_sym_let] = "let",
  [sym_identifier] = "identifier",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [sym_string_content] = "string_content",
  [sym_interpolated_string_content] = "interpolated_string_content",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_DOLLAR_DQUOTE] = "$\"",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_AT_DQUOTE] = "@\"",
  [anon_sym_DQUOTE_DQUOTE] = "\"\"",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_PLUS_PLUS] = "++",
  [anon_sym_DASH_DASH] = "--",
  [anon_sym_DASH] = "-",
  [anon_sym_BANG] = "!",
  [anon_sym_TILDE] = "~",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_local_statement] = "local_statement",
  [sym__initVar] = "_initVar",
  [sym_let_statement] = "let_statement",
  [sym__expression] = "_expression",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_simple_string] = "simple_string",
  [sym_interpolated_string] = "interpolated_string",
  [sym_interpolation] = "interpolation",
  [sym_verbatim_string] = "verbatim_string",
  [sym_verbatim_quotes] = "verbatim_quotes",
  [sym_boolean] = "boolean",
  [sym_unary_expression] = "unary_expression",
  [sym__unary_post_expression] = "_unary_post_expression",
  [sym__unary_pre_expression] = "_unary_pre_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_add] = "add",
  [sym_substract] = "substract",
  [sym_multiply] = "multiply",
  [sym_divide] = "divide",
  [sym_mod] = "mod",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_interpolated_string_repeat1] = "interpolated_string_repeat1",
  [aux_sym_verbatim_string_repeat1] = "verbatim_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_local] = anon_sym_local,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_let] = anon_sym_let,
  [sym_identifier] = sym_identifier,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [sym_string_content] = sym_string_content,
  [sym_interpolated_string_content] = sym_interpolated_string_content,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_DOLLAR_DQUOTE] = anon_sym_DOLLAR_DQUOTE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_AT_DQUOTE] = anon_sym_AT_DQUOTE,
  [anon_sym_DQUOTE_DQUOTE] = anon_sym_DQUOTE_DQUOTE,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_PLUS_PLUS] = anon_sym_PLUS_PLUS,
  [anon_sym_DASH_DASH] = anon_sym_DASH_DASH,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_local_statement] = sym_local_statement,
  [sym__initVar] = sym__initVar,
  [sym_let_statement] = sym_let_statement,
  [sym__expression] = sym__expression,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_simple_string] = sym_simple_string,
  [sym_interpolated_string] = sym_interpolated_string,
  [sym_interpolation] = sym_interpolation,
  [sym_verbatim_string] = sym_verbatim_string,
  [sym_verbatim_quotes] = sym_verbatim_quotes,
  [sym_boolean] = sym_boolean,
  [sym_unary_expression] = sym_unary_expression,
  [sym__unary_post_expression] = sym__unary_post_expression,
  [sym__unary_pre_expression] = sym__unary_pre_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_add] = sym_add,
  [sym_substract] = sym_substract,
  [sym_multiply] = sym_multiply,
  [sym_divide] = sym_divide,
  [sym_mod] = sym_mod,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_interpolated_string_repeat1] = aux_sym_interpolated_string_repeat1,
  [aux_sym_verbatim_string_repeat1] = aux_sym_verbatim_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_local] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolated_string_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_local_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__initVar] = {
    .visible = false,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_simple_string] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolated_string] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_string] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_quotes] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__unary_post_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__unary_pre_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_add] = {
    .visible = true,
    .named = true,
  },
  [sym_substract] = {
    .visible = true,
    .named = true,
  },
  [sym_multiply] = {
    .visible = true,
    .named = true,
  },
  [sym_divide] = {
    .visible = true,
    .named = true,
  },
  [sym_mod] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_interpolated_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_verbatim_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '!', 79,
        '"', 65,
        '$', 3,
        '%', 84,
        '*', 82,
        '+', 81,
        ',', 36,
        '-', 78,
        '/', 83,
        '0', 11,
        ';', 34,
        '=', 35,
        '@', 4,
        '_', 12,
        'f', 15,
        'l', 18,
        't', 23,
        '{', 67,
        '}', 68,
        '~', 80,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 79,
        '"', 64,
        '$', 3,
        '+', 10,
        '-', 78,
        '/', 7,
        '0', 11,
        '@', 4,
        '_', 38,
        'f', 39,
        't', 43,
        '~', 80,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(47);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(65);
      if (lookahead == '/') ADVANCE(55);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(66);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(69);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(64);
      if (lookahead == '/') ADVANCE(59);
      if (lookahead == '{') ADVANCE(67);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(63);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(64);
      if (lookahead == '/') ADVANCE(55);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '/') ADVANCE(86);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(85);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '+') ADVANCE(75);
      END_STATE();
    case 11:
      if (lookahead == '.') ADVANCE(28);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == '.') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '.') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == '/') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(25);
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(71);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 26:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 27:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(51);
      END_STATE();
    case 28:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(50);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(51);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(49);
      END_STATE();
    case 31:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '%', 84,
        '*', 82,
        '+', 81,
        ',', 36,
        '-', 77,
        '/', 83,
        ';', 34,
        'l', 18,
        '}', 68,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_local);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '"') ADVANCE(86);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '"') ADVANCE(9);
      if (lookahead == '*') ADVANCE(53);
      if (lookahead == '/') ADVANCE(57);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '"') ADVANCE(9);
      if (lookahead == '*') ADVANCE(53);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '*') ADVANCE(54);
      if (lookahead == '/') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '/') ADVANCE(55);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_interpolated_string_content);
      if (lookahead == '\n') ADVANCE(63);
      if (lookahead == '"' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(86);
      if (lookahead != 0) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_interpolated_string_content);
      if (lookahead == '*') ADVANCE(61);
      if (lookahead == '/') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(63);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_interpolated_string_content);
      if (lookahead == '*') ADVANCE(60);
      if (lookahead == '/') ADVANCE(63);
      if (lookahead == '"' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(9);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_interpolated_string_content);
      if (lookahead == '*') ADVANCE(60);
      if (lookahead == '"' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(9);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_interpolated_string_content);
      if (lookahead == '/') ADVANCE(59);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_interpolated_string_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead == '"') ADVANCE(70);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_DOLLAR_DQUOTE);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_AT_DQUOTE);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_DQUOTE_DQUOTE);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(76);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(76);
      if (lookahead == '0' ||
          lookahead == '_') ADVANCE(13);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '+') ADVANCE(75);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '/') ADVANCE(86);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(86);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 31},
  [12] = {.lex_state = 31},
  [13] = {.lex_state = 31},
  [14] = {.lex_state = 31},
  [15] = {.lex_state = 31},
  [16] = {.lex_state = 31},
  [17] = {.lex_state = 31},
  [18] = {.lex_state = 31},
  [19] = {.lex_state = 31},
  [20] = {.lex_state = 31},
  [21] = {.lex_state = 31},
  [22] = {.lex_state = 31},
  [23] = {.lex_state = 31},
  [24] = {.lex_state = 31},
  [25] = {.lex_state = 31},
  [26] = {.lex_state = 31},
  [27] = {.lex_state = 31},
  [28] = {.lex_state = 31},
  [29] = {.lex_state = 31},
  [30] = {.lex_state = 31},
  [31] = {.lex_state = 31},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 5},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 5},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 5},
  [48] = {.lex_state = 6},
  [49] = {.lex_state = 14},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 14},
  [52] = {.lex_state = 14},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 14},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_local] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_AT_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE_DQUOTE] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_PLUS_PLUS] = ACTIONS(1),
    [anon_sym_DASH_DASH] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(54),
    [sym__statement] = STATE(32),
    [sym_local_statement] = STATE(32),
    [sym_let_statement] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(32),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_local] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__expression] = STATE(29),
    [sym_number] = STATE(29),
    [sym_string] = STATE(29),
    [sym_simple_string] = STATE(15),
    [sym_interpolated_string] = STATE(15),
    [sym_verbatim_string] = STATE(15),
    [sym_boolean] = STATE(29),
    [sym_unary_expression] = STATE(29),
    [sym__unary_post_expression] = STATE(14),
    [sym__unary_pre_expression] = STATE(14),
    [sym_binary_expression] = STATE(29),
    [sym_add] = STATE(18),
    [sym_substract] = STATE(18),
    [sym_multiply] = STATE(18),
    [sym_divide] = STATE(18),
    [sym_mod] = STATE(18),
    [sym_identifier] = ACTIONS(11),
    [sym_integer] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(19),
    [anon_sym_AT_DQUOTE] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_PLUS_PLUS] = ACTIONS(25),
    [anon_sym_DASH_DASH] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_TILDE] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__expression] = STATE(21),
    [sym_number] = STATE(21),
    [sym_string] = STATE(21),
    [sym_simple_string] = STATE(15),
    [sym_interpolated_string] = STATE(15),
    [sym_verbatim_string] = STATE(15),
    [sym_boolean] = STATE(21),
    [sym_unary_expression] = STATE(21),
    [sym__unary_post_expression] = STATE(14),
    [sym__unary_pre_expression] = STATE(14),
    [sym_binary_expression] = STATE(21),
    [sym_add] = STATE(18),
    [sym_substract] = STATE(18),
    [sym_multiply] = STATE(18),
    [sym_divide] = STATE(18),
    [sym_mod] = STATE(18),
    [sym_identifier] = ACTIONS(29),
    [sym_integer] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(19),
    [anon_sym_AT_DQUOTE] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_PLUS_PLUS] = ACTIONS(25),
    [anon_sym_DASH_DASH] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_TILDE] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym__expression] = STATE(30),
    [sym_number] = STATE(30),
    [sym_string] = STATE(30),
    [sym_simple_string] = STATE(15),
    [sym_interpolated_string] = STATE(15),
    [sym_verbatim_string] = STATE(15),
    [sym_boolean] = STATE(30),
    [sym_unary_expression] = STATE(30),
    [sym__unary_post_expression] = STATE(14),
    [sym__unary_pre_expression] = STATE(14),
    [sym_binary_expression] = STATE(30),
    [sym_add] = STATE(18),
    [sym_substract] = STATE(18),
    [sym_multiply] = STATE(18),
    [sym_divide] = STATE(18),
    [sym_mod] = STATE(18),
    [sym_identifier] = ACTIONS(31),
    [sym_integer] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(19),
    [anon_sym_AT_DQUOTE] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_PLUS_PLUS] = ACTIONS(25),
    [anon_sym_DASH_DASH] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_TILDE] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym__expression] = STATE(31),
    [sym_number] = STATE(31),
    [sym_string] = STATE(31),
    [sym_simple_string] = STATE(15),
    [sym_interpolated_string] = STATE(15),
    [sym_verbatim_string] = STATE(15),
    [sym_boolean] = STATE(31),
    [sym_unary_expression] = STATE(31),
    [sym__unary_post_expression] = STATE(14),
    [sym__unary_pre_expression] = STATE(14),
    [sym_binary_expression] = STATE(31),
    [sym_add] = STATE(18),
    [sym_substract] = STATE(18),
    [sym_multiply] = STATE(18),
    [sym_divide] = STATE(18),
    [sym_mod] = STATE(18),
    [sym_identifier] = ACTIONS(33),
    [sym_integer] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(19),
    [anon_sym_AT_DQUOTE] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_PLUS_PLUS] = ACTIONS(25),
    [anon_sym_DASH_DASH] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_TILDE] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym__expression] = STATE(20),
    [sym_number] = STATE(20),
    [sym_string] = STATE(20),
    [sym_simple_string] = STATE(15),
    [sym_interpolated_string] = STATE(15),
    [sym_verbatim_string] = STATE(15),
    [sym_boolean] = STATE(20),
    [sym_unary_expression] = STATE(20),
    [sym__unary_post_expression] = STATE(14),
    [sym__unary_pre_expression] = STATE(14),
    [sym_binary_expression] = STATE(20),
    [sym_add] = STATE(18),
    [sym_substract] = STATE(18),
    [sym_multiply] = STATE(18),
    [sym_divide] = STATE(18),
    [sym_mod] = STATE(18),
    [sym_identifier] = ACTIONS(35),
    [sym_integer] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(19),
    [anon_sym_AT_DQUOTE] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_PLUS_PLUS] = ACTIONS(25),
    [anon_sym_DASH_DASH] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_TILDE] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym__expression] = STATE(26),
    [sym_number] = STATE(26),
    [sym_string] = STATE(26),
    [sym_simple_string] = STATE(15),
    [sym_interpolated_string] = STATE(15),
    [sym_verbatim_string] = STATE(15),
    [sym_boolean] = STATE(26),
    [sym_unary_expression] = STATE(26),
    [sym__unary_post_expression] = STATE(14),
    [sym__unary_pre_expression] = STATE(14),
    [sym_binary_expression] = STATE(26),
    [sym_add] = STATE(18),
    [sym_substract] = STATE(18),
    [sym_multiply] = STATE(18),
    [sym_divide] = STATE(18),
    [sym_mod] = STATE(18),
    [sym_identifier] = ACTIONS(37),
    [sym_integer] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(19),
    [anon_sym_AT_DQUOTE] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_PLUS_PLUS] = ACTIONS(25),
    [anon_sym_DASH_DASH] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_TILDE] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [sym__expression] = STATE(27),
    [sym_number] = STATE(27),
    [sym_string] = STATE(27),
    [sym_simple_string] = STATE(15),
    [sym_interpolated_string] = STATE(15),
    [sym_verbatim_string] = STATE(15),
    [sym_boolean] = STATE(27),
    [sym_unary_expression] = STATE(27),
    [sym__unary_post_expression] = STATE(14),
    [sym__unary_pre_expression] = STATE(14),
    [sym_binary_expression] = STATE(27),
    [sym_add] = STATE(18),
    [sym_substract] = STATE(18),
    [sym_multiply] = STATE(18),
    [sym_divide] = STATE(18),
    [sym_mod] = STATE(18),
    [sym_identifier] = ACTIONS(39),
    [sym_integer] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(19),
    [anon_sym_AT_DQUOTE] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_PLUS_PLUS] = ACTIONS(25),
    [anon_sym_DASH_DASH] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_TILDE] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [sym__expression] = STATE(28),
    [sym_number] = STATE(28),
    [sym_string] = STATE(28),
    [sym_simple_string] = STATE(15),
    [sym_interpolated_string] = STATE(15),
    [sym_verbatim_string] = STATE(15),
    [sym_boolean] = STATE(28),
    [sym_unary_expression] = STATE(28),
    [sym__unary_post_expression] = STATE(14),
    [sym__unary_pre_expression] = STATE(14),
    [sym_binary_expression] = STATE(28),
    [sym_add] = STATE(18),
    [sym_substract] = STATE(18),
    [sym_multiply] = STATE(18),
    [sym_divide] = STATE(18),
    [sym_mod] = STATE(18),
    [sym_identifier] = ACTIONS(41),
    [sym_integer] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(19),
    [anon_sym_AT_DQUOTE] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_PLUS_PLUS] = ACTIONS(25),
    [anon_sym_DASH_DASH] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_TILDE] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [sym__expression] = STATE(12),
    [sym_number] = STATE(12),
    [sym_string] = STATE(12),
    [sym_simple_string] = STATE(15),
    [sym_interpolated_string] = STATE(15),
    [sym_verbatim_string] = STATE(15),
    [sym_boolean] = STATE(12),
    [sym_unary_expression] = STATE(12),
    [sym__unary_post_expression] = STATE(14),
    [sym__unary_pre_expression] = STATE(14),
    [sym_binary_expression] = STATE(12),
    [sym_add] = STATE(18),
    [sym_substract] = STATE(18),
    [sym_multiply] = STATE(18),
    [sym_divide] = STATE(18),
    [sym_mod] = STATE(18),
    [sym_identifier] = ACTIONS(43),
    [sym_integer] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(19),
    [anon_sym_AT_DQUOTE] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_PLUS_PLUS] = ACTIONS(25),
    [anon_sym_DASH_DASH] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_TILDE] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_SLASH,
    ACTIONS(45), 10,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_let,
      anon_sym_RBRACE,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [21] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_DASH,
    ACTIONS(53), 1,
      anon_sym_PLUS,
    ACTIONS(55), 1,
      anon_sym_SLASH,
    ACTIONS(49), 10,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_let,
      anon_sym_RBRACE,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [46] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_SLASH,
    ACTIONS(57), 10,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_let,
      anon_sym_RBRACE,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [67] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_SLASH,
    ACTIONS(61), 10,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_let,
      anon_sym_RBRACE,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [88] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_SLASH,
    ACTIONS(65), 10,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_let,
      anon_sym_RBRACE,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [109] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_SLASH,
    ACTIONS(69), 10,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_let,
      anon_sym_RBRACE,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [130] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_SLASH,
    ACTIONS(73), 10,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_let,
      anon_sym_RBRACE,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [151] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_SLASH,
    ACTIONS(77), 10,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_let,
      anon_sym_RBRACE,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [172] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_SLASH,
    ACTIONS(81), 10,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_let,
      anon_sym_RBRACE,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [193] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_SLASH,
    ACTIONS(85), 10,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_let,
      anon_sym_RBRACE,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [214] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_DASH,
    ACTIONS(53), 1,
      anon_sym_PLUS,
    ACTIONS(91), 1,
      anon_sym_STAR,
    ACTIONS(93), 1,
      anon_sym_SLASH,
    ACTIONS(95), 1,
      anon_sym_PERCENT,
    ACTIONS(89), 8,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_let,
      anon_sym_RBRACE,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
  [243] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_SLASH,
    ACTIONS(97), 10,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_let,
      anon_sym_RBRACE,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [264] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_SLASH,
    ACTIONS(101), 10,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_let,
      anon_sym_RBRACE,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [285] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_SLASH,
    ACTIONS(105), 10,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_let,
      anon_sym_RBRACE,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [306] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_SLASH,
    ACTIONS(109), 10,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_let,
      anon_sym_RBRACE,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [327] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_SLASH,
    ACTIONS(113), 10,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_let,
      anon_sym_RBRACE,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [348] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_DASH,
    ACTIONS(53), 1,
      anon_sym_PLUS,
    ACTIONS(119), 1,
      anon_sym_SLASH,
    ACTIONS(117), 10,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_let,
      anon_sym_RBRACE,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [373] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_DASH,
    ACTIONS(53), 1,
      anon_sym_PLUS,
    ACTIONS(123), 1,
      anon_sym_SLASH,
    ACTIONS(121), 10,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_let,
      anon_sym_RBRACE,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [398] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_DASH,
    ACTIONS(53), 1,
      anon_sym_PLUS,
    ACTIONS(91), 1,
      anon_sym_STAR,
    ACTIONS(93), 1,
      anon_sym_SLASH,
    ACTIONS(95), 1,
      anon_sym_PERCENT,
    ACTIONS(127), 1,
      anon_sym_COMMA,
    ACTIONS(129), 2,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
    ACTIONS(125), 4,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_let,
  [430] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_DASH,
    ACTIONS(53), 1,
      anon_sym_PLUS,
    ACTIONS(91), 1,
      anon_sym_STAR,
    ACTIONS(93), 1,
      anon_sym_SLASH,
    ACTIONS(95), 1,
      anon_sym_PERCENT,
    ACTIONS(129), 2,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
    ACTIONS(131), 3,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_let,
  [458] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_DASH,
    ACTIONS(53), 1,
      anon_sym_PLUS,
    ACTIONS(91), 1,
      anon_sym_STAR,
    ACTIONS(93), 1,
      anon_sym_SLASH,
    ACTIONS(95), 1,
      anon_sym_PERCENT,
    ACTIONS(133), 1,
      anon_sym_RBRACE,
    ACTIONS(129), 2,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
  [484] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_local,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(135), 1,
      ts_builtin_sym_end,
    STATE(33), 4,
      sym__statement,
      sym_local_statement,
      sym_let_statement,
      aux_sym_source_file_repeat1,
  [503] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      ts_builtin_sym_end,
    ACTIONS(139), 1,
      anon_sym_local,
    ACTIONS(142), 1,
      anon_sym_let,
    STATE(33), 4,
      sym__statement,
      sym_local_statement,
      sym_let_statement,
      aux_sym_source_file_repeat1,
  [522] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_EQ,
    ACTIONS(149), 1,
      anon_sym_COMMA,
    ACTIONS(145), 4,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_let,
  [538] = 5,
    ACTIONS(151), 1,
      sym_interpolated_string_content,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    ACTIONS(155), 1,
      anon_sym_LBRACE,
    ACTIONS(157), 1,
      sym_comment,
    STATE(37), 2,
      sym_interpolation,
      aux_sym_interpolated_string_repeat1,
  [555] = 5,
    ACTIONS(157), 1,
      sym_comment,
    ACTIONS(159), 1,
      sym_string_content,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    ACTIONS(163), 1,
      anon_sym_DQUOTE_DQUOTE,
    STATE(40), 2,
      sym_verbatim_quotes,
      aux_sym_verbatim_string_repeat1,
  [572] = 5,
    ACTIONS(155), 1,
      anon_sym_LBRACE,
    ACTIONS(157), 1,
      sym_comment,
    ACTIONS(165), 1,
      sym_interpolated_string_content,
    ACTIONS(167), 1,
      anon_sym_DQUOTE,
    STATE(38), 2,
      sym_interpolation,
      aux_sym_interpolated_string_repeat1,
  [589] = 5,
    ACTIONS(157), 1,
      sym_comment,
    ACTIONS(169), 1,
      sym_interpolated_string_content,
    ACTIONS(172), 1,
      anon_sym_DQUOTE,
    ACTIONS(174), 1,
      anon_sym_LBRACE,
    STATE(38), 2,
      sym_interpolation,
      aux_sym_interpolated_string_repeat1,
  [606] = 5,
    ACTIONS(157), 1,
      sym_comment,
    ACTIONS(177), 1,
      sym_string_content,
    ACTIONS(180), 1,
      anon_sym_DQUOTE,
    ACTIONS(182), 1,
      anon_sym_DQUOTE_DQUOTE,
    STATE(39), 2,
      sym_verbatim_quotes,
      aux_sym_verbatim_string_repeat1,
  [623] = 5,
    ACTIONS(157), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_DQUOTE_DQUOTE,
    ACTIONS(185), 1,
      sym_string_content,
    ACTIONS(187), 1,
      anon_sym_DQUOTE,
    STATE(39), 2,
      sym_verbatim_quotes,
      aux_sym_verbatim_string_repeat1,
  [640] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 4,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_let,
  [650] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_SEMI,
    ACTIONS(189), 3,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_let,
  [662] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 4,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_SEMI,
      anon_sym_let,
  [672] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 3,
      ts_builtin_sym_end,
      anon_sym_local,
      anon_sym_let,
  [681] = 2,
    ACTIONS(157), 1,
      sym_comment,
    ACTIONS(197), 3,
      sym_string_content,
      anon_sym_DQUOTE,
      anon_sym_DQUOTE_DQUOTE,
  [690] = 2,
    ACTIONS(157), 1,
      sym_comment,
    ACTIONS(199), 3,
      sym_string_content,
      anon_sym_DQUOTE,
      anon_sym_DQUOTE_DQUOTE,
  [699] = 2,
    ACTIONS(157), 1,
      sym_comment,
    ACTIONS(201), 3,
      sym_interpolated_string_content,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
  [708] = 3,
    ACTIONS(157), 1,
      sym_comment,
    ACTIONS(203), 1,
      sym_string_content,
    ACTIONS(205), 1,
      anon_sym_DQUOTE,
  [718] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      sym_identifier,
    STATE(42), 1,
      sym__initVar,
  [728] = 3,
    ACTIONS(157), 1,
      sym_comment,
    ACTIONS(209), 1,
      sym_string_content,
    ACTIONS(211), 1,
      anon_sym_DQUOTE_DQUOTE,
  [738] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      sym_identifier,
    STATE(41), 1,
      sym__initVar,
  [748] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      sym_identifier,
    STATE(43), 1,
      sym__initVar,
  [758] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      anon_sym_EQ,
  [765] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      ts_builtin_sym_end,
  [772] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_DQUOTE_DQUOTE,
  [779] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_DQUOTE,
  [786] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 21,
  [SMALL_STATE(13)] = 46,
  [SMALL_STATE(14)] = 67,
  [SMALL_STATE(15)] = 88,
  [SMALL_STATE(16)] = 109,
  [SMALL_STATE(17)] = 130,
  [SMALL_STATE(18)] = 151,
  [SMALL_STATE(19)] = 172,
  [SMALL_STATE(20)] = 193,
  [SMALL_STATE(21)] = 214,
  [SMALL_STATE(22)] = 243,
  [SMALL_STATE(23)] = 264,
  [SMALL_STATE(24)] = 285,
  [SMALL_STATE(25)] = 306,
  [SMALL_STATE(26)] = 327,
  [SMALL_STATE(27)] = 348,
  [SMALL_STATE(28)] = 373,
  [SMALL_STATE(29)] = 398,
  [SMALL_STATE(30)] = 430,
  [SMALL_STATE(31)] = 458,
  [SMALL_STATE(32)] = 484,
  [SMALL_STATE(33)] = 503,
  [SMALL_STATE(34)] = 522,
  [SMALL_STATE(35)] = 538,
  [SMALL_STATE(36)] = 555,
  [SMALL_STATE(37)] = 572,
  [SMALL_STATE(38)] = 589,
  [SMALL_STATE(39)] = 606,
  [SMALL_STATE(40)] = 623,
  [SMALL_STATE(41)] = 640,
  [SMALL_STATE(42)] = 650,
  [SMALL_STATE(43)] = 662,
  [SMALL_STATE(44)] = 672,
  [SMALL_STATE(45)] = 681,
  [SMALL_STATE(46)] = 690,
  [SMALL_STATE(47)] = 699,
  [SMALL_STATE(48)] = 708,
  [SMALL_STATE(49)] = 718,
  [SMALL_STATE(50)] = 728,
  [SMALL_STATE(51)] = 738,
  [SMALL_STATE(52)] = 748,
  [SMALL_STATE(53)] = 758,
  [SMALL_STATE(54)] = 765,
  [SMALL_STATE(55)] = 772,
  [SMALL_STATE(56)] = 779,
  [SMALL_STATE(57)] = 786,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolated_string, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolated_string, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mod, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mod, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_string, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_simple_string, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_string, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim_string, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_substract, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_substract, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__unary_pre_expression, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__unary_post_expression, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__unary_post_expression, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolated_string, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolated_string, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_string, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim_string, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_string, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_simple_string, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_add, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiply, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiply, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_divide, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_divide, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__initVar, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 4, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__initVar, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [169] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_interpolated_string_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_interpolated_string_repeat1, 2, 0, 0),
  [174] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_interpolated_string_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [177] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_verbatim_string_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_verbatim_string_repeat1, 2, 0, 0),
  [182] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_verbatim_string_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_statement, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__initVar, 5, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_statement, 3, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim_quotes, 3, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim_quotes, 2, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [215] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_quirrel(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "quirrel",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
